package com.jonso.ffighter;

/**
 * This Spawner spawns in Enemies at its X position
 * and one of the three Y-axis heights on a random timer.
 *
 * @author Jonathan So
 */
public class Spawner {

    private GameScreen game; // Used to add Enemies to the game.

    private int x, y, yHeight; // Position and height of one vertical "level"
    private float currWait; // Wait time before spawning.

    private final float MIN_WAIT = 1/3f;
    private final float MAX_WAIT = 4/3f;

    /**
     * Constructor that specifies a Spawner at a location.
     * @param x init X position.
     * @param y init Y position.
     * @param yHeight Height of one vertical "level".
     * @param game GameScreen ref.
     */
    public Spawner(int x, int y, int yHeight, GameScreen game) {
        this.x = x;
        this.y = y;
        this.yHeight = yHeight;
        this.game = game;
    }

    /**
     * Update the timer waiting for the next enemy spawn.
     * @param delta Time between previous update and now.
     */
    public void updateTimer(float delta) {
        currWait -= delta;
        if (currWait <= 0) {
            spawn(Math.random());
        }
    }

    /**
     * Spawn in a new enemy at a random height and reset the timer
     * @param rand A double random number generated by Math.random().
     */
    private void spawn(double rand) {
        // Reset the timer
        currWait = (float) (rand * (MAX_WAIT - MIN_WAIT)) + MIN_WAIT;
        // Spawn in an enemy based on height
        if (rand < 1/3f) {
            game.addEnemy(x, y);
        } else if (rand < 2/3f) {
            game.addEnemy(x, y + yHeight);
        } else {
            game.addEnemy(x, y + (yHeight * 2));
        }
    }

}
